# Generated by Django 4.2.11 on 2024-06-17 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactgroup',
            options={'ordering': ('created_at',), 'verbose_name': 'Группа контактов', 'verbose_name_plural': 'Группы контактов'},
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='url',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создана'),
            preserve_default=False,
        ),
    ]
