# Generated by Django 4.2.11 on 2024-06-20 13:47

import apps.contact_groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_groups', '0004_rename_name_contactgroup_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='file_id',
            field=models.BigIntegerField(default=apps.contact_groups.models.default_uid, unique=True, verbose_name='ID файла'),
        ),
    ]
