# Generated by Django 4.2.11 on 2024-06-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_groups', '0005_alter_contactgroup_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='file_id',
        ),
    ]
