# Generated by Django 4.2.11 on 2024-06-20 16:03

import apps.contact_groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_groups', '0006_remove_contactgroup_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='file_id',
            field=models.CharField(default=apps.contact_groups.models.default_uid, unique=True, verbose_name='ID файла'),
        ),
    ]
