# Generated by Django 4.2.11 on 2024-06-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_groups', '0007_contactgroup_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='file_id',
        ),
    ]
