# Generated by Django 4.2.11 on 2024-06-16 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ('created_at',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
