# Generated by Django 4.2.11 on 2024-06-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0002_alter_messagetemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='user',
        ),
    ]
