# Generated by Django 4.2.11 on 2024-06-13 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message_templates', '0001_initial'),
        ('contact_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, unique=True, verbose_name='Название')),
                ('contact_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='contact_groups.contactgroup', verbose_name='Группа контактов')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='message_templates.messagetemplate', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шаблон оповещения',
                'verbose_name_plural': 'Шаблоны оповещений',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_queue', 'В очереди'), ('in_processing', 'В обработке'), ('delivered', 'доставлено')], default='in_processing', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('notification_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate', verbose_name='Шаблон оповещения')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ('id',),
            },
        ),
    ]
