# Generated by Django 4.2.11 on 2024-06-23 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ('created_at',), 'verbose_name': 'Шаблон оповещения', 'verbose_name_plural': 'Шаблоны оповещений'},
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='message',
            new_name='message_template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='user',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('in_queue', 'в очереди'), ('in_processing', 'в обработке'), ('delivered', 'доставлено')], default='in_queue', max_length=15, verbose_name='Статус'),
        ),
    ]
