# Generated by Django 4.2.11 on 2024-06-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationtemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='SentNotification',
        ),
        migrations.AlterModelOptions(
            name='sentnotification',
            options={'ordering': ('created_at',), 'verbose_name': 'Оповещение', 'verbose_name_plural': 'Оповещения'},
        ),
    ]
