# Generated by Django 4.2.11 on 2024-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notification_sentnotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentnotification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sentnotification',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
    ]
