# Generated by Django 4.2.11 on 2024-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_sentnotification_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentnotification',
            name='status',
            field=models.CharField(choices=[('в очереди', 'в очереди'), ('в обработке', 'в обработке'), ('доставлено', 'доставлено')], default='в очереди', max_length=15, verbose_name='Статус'),
        ),
    ]
